### ISSUE TITLE
build fail on master

### ISSUE THREAD

**Issue by cenyG** [shadowsocks/shadowsocks-rust#1039]
```   
Compiling shadowsocks v1.15.0 (C:\*\shadowsocks-rust\crates\shadowsocks)
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> C:\*\.cargo\registry\src\github.com-1ecc6299db9ec823\anyhow-1.0.66\src\lib.rs:214:32
    |
214 | #![cfg_attr(backtrace, feature(error_generic_member_access, provide_any))]
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
   --> C:\*\.cargo\registry\src\github.com-1ecc6299db9ec823\anyhow-1.0.66\src\lib.rs:214:61
    |
214 | #![cfg_attr(backtrace, feature(error_generic_member_access, provide_any))]
    |                                                             ^^^^^^^^^^^
```

OS: Windows 10

`rustc 1.65.0 (897e37553 2022-11-02)`

**Comment by 18o** [comment]
Same on macOS

**Comment by dev4u** [comment]
switch to nightly channel

**Comment by zonyitoo** [comment]
Couldn't reproduce with `rustc 1.65.0` on the latest master branch, please retry.

Maybe it is related to: https://github.com/rust-lang/rust/issues/99301 .

**Comment by cenyG** [comment]
I switched to nightly, I'ts now bettter but another error

```
error: internal compiler error: compiler\rustc_middle\src\ty\subst.rs:741:13: Region parameter out of range when substituting in region 'a (index=1, substs = ['_#22r])

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339\compiler\rustc_errors\src\lib.rs:1576:9
stack backtrace:
   0:     0x7ff8dcd69de2 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h568b02de54b7bdce
   1:     0x7ff8dcda5d2b - core::fmt::write::hdbe28a99ffa27961
   2:     0x7ff8dcd5ca2a - <std::io::IoSliceMut as core::fmt::Debug>::fmt::h8bdf55a2af177b34
   3:     0x7ff8dcd69b2b - std::sys::common::alloc::realloc_fallback::h9c5f975abd5f7005
   4:     0x7ff8dcd6d459 - std::panicking::default_hook::hd9afca633b19bba8
   ```
   
   ```
   query stack during panic:
#0 [typeck] type-checking `acl::<impl at crates\shadowsocks-service\src\acl\mod.rs:327:1: 327:19>::check_target_bypassed`
#1 [thir_body] building THIR for `acl::<impl at crates\shadowsocks-service\src\acl\mod.rs:327:1: 327:19>::check_target_bypassed`
#2 [mir_built] building MIR for `acl::<impl at crates\shadowsocks-service\src\acl\mod.rs:327:1: 327:19>::check_target_bypassed`
#3 [unsafety_check_result] unsafety-checking `acl::<impl at crates\shadowsocks-service\src\acl\mod.rs:327:1: 327:19>::check_target_bypassed`
#4 [mir_const] preparing `acl::<impl at crates\shadowsocks-service\src\acl\mod.rs:327:1: 327:19>::check_target_bypassed` for borrow checking
#5 [mir_promoted] processing MIR for `acl::<impl at crates\shadowsocks-service\src\acl\mod.rs:327:1: 327:19>::check_target_bypassed`
#6 [mir_borrowck] borrow-checking `acl::<impl at crates\shadowsocks-service\src\acl\mod.rs:327:1: 327:19>::check_target_bypassed`
#7 [type_of] computing type of `acl::<impl at crates\shadowsocks-service\src\acl\mod.rs:327:1: 327:19>::check_target_bypassed::{opaque#0}`
#8 [check_mod_item_types] checking item types in module `acl`
#9 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `shadowsocks-service`
```

But I think I't a pretty default story that nothing opensource works on Windows as expected without workaround, I think I could find some solutions in other issus somewhere on web but it's easier to use Linux.

**Comment by zonyitoo** [comment]
This is a BUG in the recent nightly rustc. https://github.com/rust-lang/rust/issues/102751

You could just use the stable channel (1.65.0), I couldn't reproduce your issue.
