### ISSUE TITLE
failed to run on arch linux

### ISSUE THREAD

**Issue by Delta-in-hub** [shadowsocks/shadowsocks-rust#1040]
```
❯ sslocal -b "127.0.0.1:1081" --server-url "ss://cmM0LINHQ@exmaple.com"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseCipherKindError', crates/shadowsocks/src/config.rs:402:84
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    83395 IOT instruction (core dumped)  sslocal -b "127.0.0.1:1081" --server-url 
```
```
❯ sslocal -V
shadowsocks 1.14.3
```

`Linux 6.0.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 02 Dec 2022 17:25:31 +0000 x86_64 GNU/Linux`

**Comment by zonyitoo** [comment]
Where did you get this `"ss://cmM0LINHQ@exmaple.com"`? This is not a valid SIP002 URL.

**Comment by zonyitoo** [comment]
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseCipherKindError', crates/shadowsocks/src/config.rs:402:84
```

Your provided cipher is unknown. `rc4-md5` is deprecated so it is disabled by default in `sslocal`, if you insist to use this deprecated method, you may compile `sslocal` with the stream-cipher feature enabled.
