### ISSUE TITLE
Windows下无法正确配置密码

### ISSUE THREAD

**Issue by Idealisten** [shadowsocks/shadowsocks-rust#1174]
同样的密码“bHCJe7odpdgxfodOOgbHUzNWMzTdBgwGD2rlgzPyiI45”在Linux服务端下可以正常启动，在Windows服务端下报错：thread 'main' panicked at '2022-blake3-chacha20-poly1305 is expecting a 32 bytes key, but password: bHCJe7odpdgxfodOOgbHUzNWMzTdBgwGD2rlgzPyiI45 (33 bytes after decode)', /project/crates/shadowsocks/src/config.rs:352:21

**Comment by Idealisten** [comment]
加密方式都是2022-blake3-chacha20-poly1305

**Comment by Idealisten** [comment]
如果我去掉一位，在Windows端可以正常启动，在Linux端又会报错

**Comment by zonyitoo** [comment]
I can confirm that it has exactly the same error on the other platforms:

Linux:

```
thread 'main' panicked at '2022-blake3-chacha20-poly1305 is expecting a 32 bytes key, but password: bHCJe7odpdgxfodOOgbHUzNWMzTdBgwGD2rlgzPyiI45 (33 bytes after decode)', /Users/zonyitoo/Projects/shadowsocks-rust/crates/shadowsocks/src/config.rs:352:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    4065 abort      /usr/local/bin/sslocal -s '127.0.0.1:8388' -k  -m
```

macOS

```
thread 'main' panicked at '2022-blake3-chacha20-poly1305 is expecting a 32 bytes key, but password: bHCJe7odpdgxfodOOgbHUzNWMzTdBgwGD2rlgzPyiI45 (33 bytes after decode)', /Users/zonyitoo/Projects/shadowsocks-rust/crates/shadowsocks/src/config.rs:352:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    69872 abort      sslocal -s '127.0.0.1:8388' -k 'bHCJe7odpdgxfodOOgbHUzNWMzTdBgwGD2rlgzPyiI45'
```

You can test with:

```
echo 'bHCJe7odpdgxfodOOgbHUzNWMzTdBgwGD2rlgzPyiI45' | base64 -d | xxd
00000000: 6c70 897b ba1d a5d8 317e 874e 3a06 c753  lp.{....1~.N:..S
00000010: 3356 3334 dd06 0c06 0f6a e583 33f2 888e  3V34.....j..3...
00000020: 39                                       9
```

and yes, your password is 33 bytes after decode.
