### ISSUE TITLE
ppc64le: error: failed to run custom build command for `openssl-sys v0.9.102`

### ISSUE THREAD

**Issue by vt-alt** [shadowsocks/shadowsocks-rust#1548]
There is still some problem with ppc64le. We have the same setup for all architectures and external crates are vendored.
Build error when `--features full`:
```
[00:00:22]    Compiling openssl-src v300.3.0+3.3.0
...
[00:00:28]    Compiling openssl-sys v0.9.102
...
[00:00:30]      Running `/usr/src/RPM/BUILD/shadowsocks-rust-1.19.2/target/release/build/openssl-sys-f6e232f2656b31a2/build-script-main`
[00:00:30] error: failed to run custom build command for `openssl-sys v0.9.102`
[00:00:30] note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.
[00:00:30] 
[00:00:30] Caused by:
[00:00:30]   process didn't exit successfully: `/usr/src/RPM/BUILD/shadowsocks-rust-1.19.2/target/release/build/openssl-sys-f6e232f2656b31a2/build-script-main` (exit status: 101)
[00:00:30]   --- stdout
[00:00:30]   cargo:rerun-if-env-changed=POWERPC64LE_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR
[00:00:30]   POWERPC64LE_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR unset
[00:00:30]   cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
[00:00:30]   OPENSSL_NO_VENDOR unset
[00:00:30]   cargo:rerun-if-env-changed=CC_powerpc64le-unknown-linux-gnu
[00:00:30]   CC_powerpc64le-unknown-linux-gnu = None
[00:00:30]   cargo:rerun-if-env-changed=CC_powerpc64le_unknown_linux_gnu
[00:00:30]   CC_powerpc64le_unknown_linux_gnu = None
[00:00:30]   cargo:rerun-if-env-changed=HOST_CC
[00:00:30]   HOST_CC = None
[00:00:30]   cargo:rerun-if-env-changed=CC
[00:00:30]   CC = None
[00:00:30]   cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
[00:00:30]   cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
[00:00:30]   CRATE_CC_NO_DEFAULTS = None
[00:00:30]   DEBUG = Some("false")
[00:00:30]   CARGO_CFG_TARGET_FEATURE = None
[00:00:30]   cargo:rerun-if-env-changed=CFLAGS_powerpc64le-unknown-linux-gnu
[00:00:30]   CFLAGS_powerpc64le-unknown-linux-gnu = None
[00:00:30]   cargo:rerun-if-env-changed=CFLAGS_powerpc64le_unknown_linux_gnu
[00:00:30]   CFLAGS_powerpc64le_unknown_linux_gnu = None
[00:00:30]   cargo:rerun-if-env-changed=HOST_CFLAGS
[00:00:30]   HOST_CFLAGS = None
[00:00:30]   cargo:rerun-if-env-changed=CFLAGS
[00:00:30]   CFLAGS = None
[00:00:30]   cargo:rerun-if-env-changed=AR_powerpc64le-unknown-linux-gnu
[00:00:30]   AR_powerpc64le-unknown-linux-gnu = None
[00:00:30]   cargo:rerun-if-env-changed=AR_powerpc64le_unknown_linux_gnu
[00:00:30]   AR_powerpc64le_unknown_linux_gnu = None
[00:00:30]   cargo:rerun-if-env-changed=HOST_AR
[00:00:30]   HOST_AR = None
[00:00:30]   cargo:rerun-if-env-changed=AR
[00:00:30]   AR = None
[00:00:30]   cargo:rerun-if-env-changed=ARFLAGS_powerpc64le-unknown-linux-gnu
[00:00:30]   ARFLAGS_powerpc64le-unknown-linux-gnu = None
[00:00:30]   cargo:rerun-if-env-changed=ARFLAGS_powerpc64le_unknown_linux_gnu
[00:00:30]   ARFLAGS_powerpc64le_unknown_linux_gnu = None
[00:00:30]   cargo:rerun-if-env-changed=HOST_ARFLAGS
[00:00:30]   HOST_ARFLAGS = None
[00:00:30]   cargo:rerun-if-env-changed=ARFLAGS
[00:00:30]   ARFLAGS = None
[00:00:30]   cargo:rerun-if-env-changed=RANLIB_powerpc64le-unknown-linux-gnu
[00:00:30]   RANLIB_powerpc64le-unknown-linux-gnu = None
[00:00:30]   cargo:rerun-if-env-changed=RANLIB_powerpc64le_unknown_linux_gnu
[00:00:30]   RANLIB_powerpc64le_unknown_linux_gnu = None
[00:00:30]   cargo:rerun-if-env-changed=HOST_RANLIB
[00:00:30]   HOST_RANLIB = None
[00:00:30]   cargo:rerun-if-env-changed=RANLIB
[00:00:30]   RANLIB = None
[00:00:30]   cargo:rerun-if-env-changed=RANLIBFLAGS_powerpc64le-unknown-linux-gnu
[00:00:30]   RANLIBFLAGS_powerpc64le-unknown-linux-gnu = None
[00:00:30]   cargo:rerun-if-env-changed=RANLIBFLAGS_powerpc64le_unknown_linux_gnu
[00:00:30]   RANLIBFLAGS_powerpc64le_unknown_linux_gnu = None
[00:00:30]   cargo:rerun-if-env-changed=HOST_RANLIBFLAGS
[00:00:30]   HOST_RANLIBFLAGS = None
[00:00:30]   cargo:rerun-if-env-changed=RANLIBFLAGS
[00:00:30]   RANLIBFLAGS = None
[00:00:30]   running cd "/usr/src/RPM/BUILD/shadowsocks-rust-1.19.2/target/release/build/openssl-sys-83f7ea376da3528f/out/openssl-build/build/src" && env -u CROSS_COMPILE AR="ar" CC="cc" RANLIB="ranlib" "perl" "./Configure" "--prefix=/usr/src/RPM/BUILD/shadowsocks-rust-1.19.2/target/release/build/openssl-sys-83f7ea376da3528f/out/openssl-build/install" "--openssldir=/usr/local/ssl" "no-dso" "no-shared" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "linux-ppc64le" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64"
[00:00:30] 
[00:00:30]   --- stderr
[00:00:30]   Can't locate IPC/Cmd.pm in @INC (you may need to install the IPC::Cmd module) (@INC entries checked: /usr/src/RPM/BUILD/shadowsocks-rust-1.19.2/target/release/build/openssl-sys-83f7ea376da3528f/out/openssl-build/build/src/util/perl /usr/local/lib64/perl/5.38 /usr/local/share/perl/5.38 /usr/lib64/perl5 /usr/share/perl5 /etc/perl5 /usr/lib/perl5/vendor_perl . /usr/src/RPM/BUILD/shadowsocks-rust-1.19.2/target/release/build/openssl-sys-83f7ea376da3528f/out/openssl-build/build/src/external/perl/Text-Template-1.56/lib) at /usr/src/RPM/BUILD/shadowsocks-rust-1.19.2/target/release/build/openssl-sys-83f7ea376da3528f/out/openssl-build/build/src/util/perl/OpenSSL/config.pm line 19.
[00:00:30]   BEGIN failed--compilation aborted at /usr/src/RPM/BUILD/shadowsocks-rust-1.19.2/target/release/build/openssl-sys-83f7ea376da3528f/out/openssl-build/build/src/util/perl/OpenSSL/config.pm line 19.
[00:00:30]   Compilation failed in require at ./Configure line 23.
[00:00:30]   BEGIN failed--compilation aborted at ./Configure line 23.
[00:00:30]   thread 'main' panicked at /usr/src/RPM/BUILD/shadowsocks-rust-1.19.2/vendor/openssl-src/src/lib.rs:621:9:
[00:00:30] 
[00:00:30] 
[00:00:30] 
[00:00:30]   Error configuring OpenSSL build:
[00:00:30]       Command: cd "/usr/src/RPM/BUILD/shadowsocks-rust-1.19.2/target/release/build/openssl-sys-83f7ea376da3528f/out/openssl-build/build/src" && env -u CROSS_COMPILE AR="ar" CC="cc" RANLIB="ranlib" "perl" "./Configure" "--prefix=/usr/src/RPM/BUILD/shadowsocks-rust-1.19.2/target/release/build/openssl-sys-83f7ea376da3528f/out/openssl-build/install" "--openssldir=/usr/local/ssl" "no-dso" "no-shared" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "linux-ppc64le" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64"
[00:00:30]       Exit status: exit status: 2
[00:00:30] 
[00:00:30] 
[00:00:30]       
[00:00:30]   stack backtrace:
[00:00:30]      0:        0x134882824 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9aaef24e85ac90df
[00:00:30]      1:        0x1348dbf88 - core::fmt::write::h1df794f42b602d1b
[00:00:30]      2:        0x1348a9c00 - std::io::Write::write_fmt::hc317cca5b5adab39
[00:00:30]      3:        0x1348825e0 - std::sys_common::backtrace::print::hac2f35db09b5a161
[00:00:30]      4:        0x134883ef8 - std::panicking::default_hook::{{closure}}::he9a7d5ae7eee6585
[00:00:30]      5:        0x134883a88 - std::panicking::default_hook::h45455e7aeaafcee3
[00:00:30]      6:        0x1348844f4 - std::panicking::rust_panic_with_hook::he5382203f61b6128
[00:00:30]      7:        0x134884334 - std::panicking::begin_panic_handler::{{closure}}::hf63a43dc6e57ba1f
[00:00:30]      8:        0x134882de8 - std::sys_common::backtrace::__rust_end_short_backtrace::ha959ae3c296fbe08
[00:00:30]      9:        0x134883f88 - rust_begin_unwind
[00:00:30]     10:        0x1347e9584 - core::panicking::panic_fmt::h8c32ad069280b870
[00:00:30]     11:        0x134829548 - openssl_src::Build::run_command::hb7a20ab14fa27d1a
[00:00:30]                                  at /usr/src/RPM/BUILD/shadowsocks-rust-1.19.2/vendor/openssl-src/src/lib.rs:621:9
[00:00:30]     12:        0x13482814c - openssl_src::Build::build::h0c50331a29ff30ff
[00:00:30]                                  at /usr/src/RPM/BUILD/shadowsocks-rust-1.19.2/vendor/openssl-src/src/lib.rs:555:9
[00:00:30]     13:        0x1347f9d64 - build_script_main::find_vendored::get_openssl::h4fe81a9e9a0f5aca
[00:00:30]                                  at /usr/src/RPM/BUILD/shadowsocks-rust-1.19.2/vendor/openssl-sys/build/find_vendored.rs:5:21
[00:00:30]     14:        0x1347ecd08 - build_script_main::find_openssl::h90753d7973685538
[00:00:30]                                  at /usr/src/RPM/BUILD/shadowsocks-rust-1.19.2/vendor/openssl-sys/build/main.rs:53:20
[00:00:30]     15:        0x1347ecd08 - build_script_main::main::h98123465ce999aa0
[00:00:30]                                  at /usr/src/RPM/BUILD/shadowsocks-rust-1.19.2/vendor/openssl-sys/build/main.rs:81:35
[00:00:30]     16:        0x1347fa634 - core::ops::function::FnOnce::call_once::h4728fca1a237514a
[00:00:30]                                  at /usr/src/RPM/BUILD/rust-1.78.0/library/core/src/ops/function.rs:250:5
[00:00:30]     17:        0x1347fa634 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1fb86cf45194b03c
[00:00:30]                                  at /usr/src/RPM/BUILD/rust-1.78.0/library/std/src/sys_common/backtrace.rs:155:18
[00:00:30]     18:        0x1347fa87c - std::rt::lang_start::{{closure}}::he4ed9d40c9eb8fd6
[00:00:30]                                  at /usr/src/RPM/BUILD/rust-1.78.0/library/std/src/rt.rs:166:18
[00:00:30]     19:        0x13487d998 - std::rt::lang_start_internal::h6e8a597012801e4e
[00:00:30]     20:        0x1347ef8d4 - main
[00:00:30]     21:     0x7fffaca6a02c - <unknown>
[00:00:30]     22:     0x7fffaca6a26c - __libc_start_main
[00:00:30]     23:                0x0 - <unknown>
[00:00:30] warning: build failed, waiting for other jobs to finish...
```
Temporary build log https://git.altlinux.org/tasks/350194/build/100/ppc64le/log

Yes it tries to compile `openssl-src` which does not happen on other architectures.

Also, it does not fail with `default` features so for ppc64le I disable `--features full` as a workaround. But maybe you'lll have other valuable suggestions.

ps. For example x86-64 log which is successful https://git.altlinux.org/tasks/350194/build/100/x86_64/log it does not even mention building `openssl-sys` or `openssl-src`.

**Comment by zonyitoo** [comment]
Did you tried: https://stackoverflow.com/questions/70464585/error-when-installing-openssl-3-0-1-cant-locate-ipc-cmd-pm-in-inc .

**Comment by vt-alt** [comment]
Yes. But I reluctant to compile openssl-sys by the two reasons -- we have `openssl-devel` package so it don't need to be compiled[1], and all other our architectures (x86, x86-64, aarch64) do not try to compile `openssl-src`.

[1] https://docs.rs/openssl/latest/openssl/
>      "The openssl-sys crate will automatically detect OpenSSL installations
>      via Homebrew on macOS and vcpkg on Windows. Additionally, it will use
>      pkg-config on Unix-like systems to find the system installation."

If you think things behave as they should and is not a problem of shadowsocks-rust feel free to close the issue.

ps. If I add `perl-IPC-Cmd` there is still build problem on ppc64le:
```
[00:00:30]      Running `/usr/src/RPM/BUILD/shadowsocks-rust-1.19.2/target/release/build/openssl-sys-f6e232f2656b31a2/build-script-main`
[00:00:31]      Running `/usr/src/RPM/BUILD/shadowsocks-rust-1.19.2/target/release/build/ring-a7f55ee1d592e166/build-script-build`
[00:00:31]      Running `/usr/src/RPM/BUILD/shadowsocks-rust-1.19.2/target/release/build/ring-255c85ccdbacd6e1/build-script-build`
[00:00:31] error: failed to run custom build command for `ring v0.16.20`
[00:00:31] note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.
[00:00:31] 
[00:00:31] Caused by:
[00:00:31]   process didn't exit successfully: `/usr/src/RPM/BUILD/shadowsocks-rust-1.19.2/target/release/build/ring-255c85ccdbacd6e1/build-script-build` (exit status: 101)
[00:00:31]   --- stderr
[00:00:31]   thread 'main' panicked at /usr/src/RPM/BUILD/shadowsocks-rust-1.19.2/vendor/ring-0.16.20/build.rs:358:10:
[00:00:31]   called `Option::unwrap()` on a `None` value
[00:00:31]   stack backtrace:
[00:00:31]      0:        0x107c56924 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9aaef24e85ac90df
[00:00:31]      1:        0x107cade08 - core::fmt::write::h1df794f42b602d1b
[00:00:31]      2:        0x107c7d1c0 - std::io::Write::write_fmt::hc317cca5b5adab39
[00:00:31]      3:        0x107c566e0 - std::sys_common::backtrace::print::hac2f35db09b5a161
[00:00:31]      4:        0x107c57ff8 - std::panicking::default_hook::{{closure}}::he9a7d5ae7eee6585
[00:00:31]      5:        0x107c57b88 - std::panicking::default_hook::h45455e7aeaafcee3
[00:00:31]      6:        0x107c585f4 - std::panicking::rust_panic_with_hook::he5382203f61b6128
[00:00:31]      7:        0x107c583fc - std::panicking::begin_panic_handler::{{closure}}::hf63a43dc6e57ba1f
[00:00:31]      8:        0x107c56ee8 - std::sys_common::backtrace::__rust_end_short_backtrace::ha959ae3c296fbe08
[00:00:31]      9:        0x107c58088 - rust_begin_unwind
[00:00:31]     10:        0x107bf51b4 - core::panicking::panic_fmt::h8c32ad069280b870
[00:00:31]     11:        0x107bf52b0 - core::panicking::panic::hc76b8121d084beaf
[00:00:31]     12:        0x107bf5118 - core::option::unwrap_failed::h97ac0b7440fe1624
[00:00:31]     13:        0x107bfab3c - build_script_build::build_c_code::h7d1d873ee3b537b1
[00:00:31]     14:        0x107bfab3c - build_script_build::ring_build_rs_main::h18173ca0a03f0407
[00:00:31]                                  at /usr/src/RPM/BUILD/shadowsocks-rust-1.19.2/vendor/ring-0.16.20/build.rs:279:5
[00:00:31]     15:        0x107bfab3c - build_script_build::main::hc165cf990bd29a4d
[00:00:31]                                  at /usr/src/RPM/BUILD/shadowsocks-rust-1.19.2/vendor/ring-0.16.20/build.rs:240:13
[00:00:31]     16:        0x107c01d74 - core::ops::function::FnOnce::call_once::h91201ecc3a142ae3
[00:00:31]                                  at /usr/src/RPM/BUILD/rust-1.78.0/library/core/src/ops/function.rs:250:5
[00:00:31]     17:        0x107c01d74 - std::sys_common::backtrace::__rust_begin_short_backtrace::hcd4c017bf8b25688
[00:00:31]                                  at /usr/src/RPM/BUILD/rust-1.78.0/library/std/src/sys_common/backtrace.rs:155:18
[00:00:31]     18:        0x107c01dbc - std::rt::lang_start::{{closure}}::h0b73c1218257a031
[00:00:31]                                  at /usr/src/RPM/BUILD/rust-1.78.0/library/std/src/rt.rs:166:18
[00:00:31]     19:        0x107c51a98 - std::rt::lang_start_internal::h6e8a597012801e4e
[00:00:31]     20:        0x107bfdea4 - main
[00:00:31]     21:     0x7fffa58aa02c - <unknown>
[00:00:31]     22:     0x7fffa58aa26c - __libc_start_main
[00:00:31]     23:                0x0 - <unknown>
[00:00:31] warning: build failed, waiting for other jobs to finish...
```
Temporary log https://git.altlinux.org/tasks/350196/build/100/ppc64le/log

**Comment by zonyitoo** [comment]
The dependency tree is:

```
├── reqwest v0.12.4
│   ├── hyper-tls v0.6.0
│   │   ├── native-tls v0.2.12
│   │   │   ├── openssl v0.10.64
│   │   │   │   └── openssl-sys v0.9.102
│   │   │   │       └── libc v0.2.155
│   │   │   │       [build-dependencies]
│   │   │   │       ├── cc v1.0.98
│   │   │   │       │   ├── jobserver v0.1.31
│   │   │   │       │   │   └── libc v0.2.155
│   │   │   │       │   ├── libc v0.2.155
│   │   │   │       │   └── once_cell v1.19.0
│   │   │   │       ├── openssl-src v300.3.0+3.3.0
│   │   │   │       │   └── cc v1.0.98 (*)
│   │   │   │       ├── pkg-config v0.3.30
│   │   │   │       └── vcpkg v0.2.15
│   │   │   ├── openssl-probe v0.1.5
│   │   │   └── openssl-sys v0.9.102 (*)
```

Try to disable the `local-online-config` feature from `full` and see if you can build successfully.

**Comment by zonyitoo** [comment]
Oh I see why on ppc64le reqwest try to compile "native-tls":

https://github.com/shadowsocks/shadowsocks-rust/blob/84eab9e082d864160e80afba04fa811a257b369f/Cargo.toml#L265-L269

Hmm. I should probably use `rust-tls` all the time.

**Comment by vt-alt** [comment]
> Try to disable the `local-online-config` feature from `full` and see if you can build successfully.

Thanks. Removing `local-online-config` from `full` bypassed openssl compilation. But problem with `ring` still remains.

**Comment by zonyitoo** [comment]
Yes, I think the reason is because the "ring" version in the dependency tree is old (v0.16). Try to disable "dns-over-h3" too and see if it compiles.

**Comment by vt-alt** [comment]
> Try to disable "dns-over-h3" too and see if it compiles.

Yes this helped. Thanks. After removing `dns-over-h3` from `full` it compiled on `ppc64le`.


```
2024-Jun-02 15:53:19 :: [x86_64] #100 shadowsocks-rust.git 1.19.2-alt1: build OK
2024-Jun-02 15:55:23 :: [i586] #100 shadowsocks-rust.git 1.19.2-alt1: build OK
2024-Jun-02 16:01:16 :: [aarch64] #100 shadowsocks-rust.git 1.19.2-alt1: build OK
2024-Jun-02 16:01:42 :: [ppc64le] #100 shadowsocks-rust.git 1.19.2-alt1: build OK

```

**Comment by zonyitoo** [comment]
Awesome. They are now working on migrating to rustls v0.23, which will also changed the cryptographic backend to aws-lc. The only thing we can do here is wait.

**Comment by vt-alt** [comment]
Thank you for the help!
