### ISSUE TITLE
ssserver崩溃退出

### ISSUE THREAD

**Issue by dev4u** [shadowsocks/shadowsocks-rust#356]
启动命令：
./ssserver --config shadowsocks.json -v --log-without-time

```json
{
  "server_port" : 1111,
  "server" : "#",
  "method" : "#",
  "mode" : "tcp_and_udp",
  "password" : "####",
  "ipv6_first": false,
  "nofile": 51200,
  "dns": "127.0.0.53",
  "no_delay": false,
  "udp_timeout": 60,
  "udp_max_associations": 3000
}
```

```log
thread 'tokio-runtime-worker' panicked at 'must be called from the context of Tokio runtime configured with either `basic_scheduler` or `threaded_scheduler`', /root/.cargo/git/checkouts/trust-dns-97a7602ad159d348/0662ab6/crates/resolver/src/name_server/connection_provider.rs:343:25
stack backtrace:
   0:     0x5584991444ef - std::backtrace_rs::backtrace::libunwind::trace::h746c3e9529d524bc
                               at /rustc/7f9c43cf98cfe1c369045399929cb098155b8374/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5584991444ef - std::backtrace_rs::backtrace::trace_unsynchronized::h84373278bfb39e0c
                               at /rustc/7f9c43cf98cfe1c369045399929cb098155b8374/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5584991444ef - std::sys_common::backtrace::_print_fmt::h517324efde750597
                               at /rustc/7f9c43cf98cfe1c369045399929cb098155b8374/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5584991444ef - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf594ab77fac89284
                               at /rustc/7f9c43cf98cfe1c369045399929cb098155b8374/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x558498fa06dc - core::fmt::write::h3868db8542c90941
                               at /rustc/7f9c43cf98cfe1c369045399929cb098155b8374/library/core/src/fmt/mod.rs:1078:17
   5:     0x558499143aff - std::io::Write::write_fmt::h3f6656f045fa877f
                               at /rustc/7f9c43cf98cfe1c369045399929cb098155b8374/library/std/src/io/mod.rs:1519:15
   6:     0x558499143520 - std::sys_common::backtrace::_print::hda7655c057c24dcc
                               at /rustc/7f9c43cf98cfe1c369045399929cb098155b8374/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x558499143520 - std::sys_common::backtrace::print::h546a6c8431d46287
                               at /rustc/7f9c43cf98cfe1c369045399929cb098155b8374/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x558499143520 - std::panicking::default_hook::{{closure}}::h006dd083853faf51
                               at /rustc/7f9c43cf98cfe1c369045399929cb098155b8374/library/std/src/panicking.rs:208:50
   9:     0x558499142dd3 - std::panicking::default_hook::hf0f9afb1017317fc
                               at /rustc/7f9c43cf98cfe1c369045399929cb098155b8374/library/std/src/panicking.rs:225:9
  10:     0x558499142dd3 - std::panicking::rust_panic_with_hook::hb7a19826c029b1d6
                               at /rustc/7f9c43cf98cfe1c369045399929cb098155b8374/library/std/src/panicking.rs:591:17
  11:     0x558499160e1d - std::panicking::begin_panic_handler::{{closure}}::hde71edcd925d0c5e
  12:     0x558499160d8e - std::sys_common::backtrace::__rust_end_short_backtrace::h8a3c7d6cea578919
                               at /rustc/7f9c43cf98cfe1c369045399929cb098155b8374/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x558499160d3d - rust_begin_unwind
                               at /rustc/7f9c43cf98cfe1c369045399929cb098155b8374/library/std/src/panicking.rs:493:5
  14:     0x558498f9df90 - core::panicking::panic_fmt::h20225113c4a2f8fd
                               at /rustc/7f9c43cf98cfe1c369045399929cb098155b8374/library/core/src/panicking.rs:92:14
  15:     0x558498fa17f2 - core::option::expect_failed::h8be1ca96ca0d69ca
                               at /rustc/7f9c43cf98cfe1c369045399929cb098155b8374/library/core/src/option.rs:1260:5
  16:     0x558498f1b6c0 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h87f76724d81d3337
  17:     0x558498f04c45 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0206c6694c5e1167
  18:     0x558498f1bc05 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h9a6985b53c47427c
  19:     0x558498eca2e5 - <trust_dns_proto::xfer::retry_dns_handle::RetrySendFuture<H> as core::future::future::Future>::poll::h1a5ca35add0a0976
  20:     0x558498ed55aa - trust_dns_resolver::caching_client::CachingClient<C,E>::inner_lookup::{{closure}}::h69806edc24e5c54c
  21:     0x558498f1dec5 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha0934acff59327ac
  22:     0x558498f156ab - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h52a8cb8ab0f0c3f9
  23:     0x558498f23769 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb807228db3becd21
  24:     0x558498f08a43 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h359663414d4034db
  25:     0x558498f21b0b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::had32ce8ecf319ee9
  26:     0x558498f1e03e - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::haab2691b2b650a88
  27:     0x558498edba76 - shadowsocks_service::server::tcprelay::TcpServerClient::serve::{{closure}}::h3f2483c9ab5bd088
  28:     0x558498f1b815 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h8e130d54f828dd24
  29:     0x558498efc065 - tokio::runtime::task::raw::poll::hdd4ac9088474dc10
  30:     0x558499192100 - tokio::runtime::thread_pool::worker::Context::run_task::hdfc9b341c910517f
  31:     0x55849919014e - tokio::runtime::task::raw::poll::hd885089221e9d626
  32:     0x55849917df06 - std::sys_common::backtrace::__rust_begin_short_backtrace::hace7e1923a600dd2
  33:     0x55849917dbf1 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h91924bcc976b600d
  34:     0x5584991712c5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hea1090dbdcecbf5a
                               at /rustc/7f9c43cf98cfe1c369045399929cb098155b8374/library/alloc/src/boxed.rs:1328:9
  35:     0x5584991712c5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8d5723d3912bd325
                               at /rustc/7f9c43cf98cfe1c369045399929cb098155b8374/library/alloc/src/boxed.rs:1328:9
  36:     0x5584991712c5 - std::sys::unix::thread::Thread::new::thread_start::hc17a425ca2995724
                               at /rustc/7f9c43cf98cfe1c369045399929cb098155b8374/library/std/src/sys/unix/thread.rs:71:17
  37:     0x7f925a7f7432 - start_thread
  38:     0x7f925a71e913 - __clone
  39:                0x0 - <unknown>
Aborted (core dumped)
```

**Comment by zonyitoo** [comment]
Related to #354 .
