### ISSUE TITLE
local No plugin operation error RUST_BACKTRACE=1

### ISSUE THREAD

**Issue by htmlrust** [shadowsocks/shadowsocks-rust#423]
publicip has been hidden

```
./sslocal -b "publicip:29849" -s "[192.168.3.169]:8388" -m "aes-256-gcm" -k "b69f7ccf-a4d5-46d6-8d8f-91869f2bb3f0"
2021-02-21T06:50:30.107621047+08:00 INFO  shadowsocks 1.9.0-alpha.6
thread 'main' panicked at 'aborted with Address not available (os error 99)', bin/sslocal.rs:432:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

```
./sslocal -b "publicip:29849" -s "192.168.3.169:8388" -m "aes-256-gcm" -k "b69f7ccf-a4d5-46d6-8d8f-91869f2bb3f0"
2021-02-21T06:53:23.345097107+08:00 INFO  shadowsocks 1.9.0-alpha.6
thread 'main' panicked at 'aborted with Address not available (os error 99)', bin/sslocal.rs:432:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

**Comment by zonyitoo** [comment]
`EADDRNOTAVAIL` means that your `publicip` is not available for binding. Please double check.

**Comment by htmlrust** [comment]
My local settings are correct. Will the client detect whether the server can be accessed and used normally when it starts?

```

 ./ssserver -s "[::]:8388" -m "aes-256-gcm" -k "hello-kitty"
2021-02-21T14:51:31.060650960+08:00 INFO  shadowsocks 1.9.0-alpha.6
2021-02-21T14:51:31.061137481+08:00 INFO  shadowsocks tcp server listening on [::]:8388, inbound address [::]:8388
```

```

./sslocal -b "127.0.0.1:1080" -s "[::1]:8388" -m "aes-256-gcm" -k "hello-kitty"
2021-02-21T15:00:25.522706199+08:00 INFO  shadowsocks 1.9.0-alpha.6
2021-02-21T15:00:25.523267755+08:00 INFO  shadowsocks socks TCP listening on 127.0.0.1:1080

```

**Comment by zonyitoo** [comment]
What do you mean? Is that related to this issue?

When `sslocal` have multiple remote servers, it will try to detect and choose the best server to connect to. If you only have one server, then it won't detect because it is pointless.

**Comment by htmlrust** [comment]
Sorry, it was my mistake. The b parameter of sslocal should be bound to the local ip, but I bound the remote ip, s is the remote ip
